In [1]:
import tensorflow as tf
import numpy as np
import random
import math

x = tf.placeholder(tf.float32, [None, 1])
y = tf.placeholder(tf.float32, [None, 1])
c = tf.placeholder(tf.int32)


def gensin(num):
    # inarr = [[random.random()] for i in xrange(num)]
    inarr = np.float32(np.random.uniform(-2*math.pi, 2*math.pi, (1, num))).T
    #inarr = tf.random_uniform([num,1], minval =)
    outarr = np.sin(inarr)
    # outarr = mapk(lambda x: [math.sin(x[0])], inarr)
    
    return inarr, outarr

fw1 = tf.get_variable("fullweights1", [1,100], initializer=tf.contrib.layers.xavier_initializer())
#asdf = tf.stop_gradient(tf.slice(fw1, [0,0],[1,c]))
w1 = tf.slice(fw1, [0,0],[1,c]) 
#w1 = tf.stop_gradient(w1)
fb1 = tf.get_variable("fullbias1", [100])
b1 = tf.slice(fb1, [0], [c])
    
h = tf.matmul(x, w1) # + b1
h2 = tf.nn.relu(h)
                           
fw2 = tf.get_variable("fullweights2", [100,1], initializer=tf.contrib.layers.xavier_initializer())
w2 = tf.slice(fw2, [0,0],[c,1])
#w2 = tf.stop_gradient(w2)
fb2 = tf.get_variable("fullbias2", [1])
b2 = tf.slice(fb2, [0], [1])
    
yhat = tf.matmul(h2, w2) + b2
    
train_step = tf.train.AdamOptimizer().minimize(tf.nn.l2_loss(yhat - y))

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

for i in xrange(10000):
    cval = 100
    inarr, outarr = gensin(10000)
    sess.run(train_step, feed_dict={x:inarr, y:outarr, c:cval})
    if i % 1000 == 0:
        inarr, outarr = gensin(1000)
        print sess.run(tf.nn.l2_loss(yhat-outarr), feed_dict={x:inarr, c:cval})
    


483.723
211.99
204.355
209.606
215.268
202.594
214.36
223.602
212.173
209.1


In [2]:
sess.run(fw1)

array([[ -1.41193414e-05,  -4.36244756e-02,   3.66338193e-02,
          2.45782398e-02,  -1.55914843e-03,   1.47654772e-01,
         -7.18229711e-02,   1.38838142e-01,  -1.47039726e-01,
          2.13103592e-01,   7.76462555e-02,  -3.31065096e-02,
         -1.61414027e-01,   2.33996609e-38,   4.14234912e-03,
         -2.40447029e-01,   1.26290902e-01,   7.05190226e-02,
          1.40796557e-01,   1.22122219e-37,   5.23377694e-02,
          2.16723487e-01,  -5.00680394e-02,  -4.56055477e-02,
         -1.55026659e-01,  -1.43749550e-01,   6.21796865e-03,
          6.00050129e-02,  -1.48593277e-01,  -1.76089585e-01,
         -2.05665067e-01,   4.64819074e-02,  -9.28762779e-02,
         -4.46784281e-04,  -4.07397188e-02,  -1.85059786e-01,
         -5.50279543e-02,   1.23728728e-02,   1.77044168e-01,
          5.12257032e-02,  -4.15780097e-37,  -1.21000692e-01,
          7.72080645e-02,   1.33501709e-01,   5.58607951e-02,
         -8.31794553e-03,   1.37871355e-01,   0.00000000e+00,
        

In [3]:
sess.run(w1, feed_dict={c:50})

array([[ -1.41193414e-05,  -4.36244756e-02,   3.66338193e-02,
          2.45782398e-02,  -1.55914843e-03,   1.47654772e-01,
         -7.18229711e-02,   1.38838142e-01,  -1.47039726e-01,
          2.13103592e-01,   7.76462555e-02,  -3.31065096e-02,
         -1.61414027e-01,   2.33996609e-38,   4.14234912e-03,
         -2.40447029e-01,   1.26290902e-01,   7.05190226e-02,
          1.40796557e-01,   1.22122219e-37,   5.23377694e-02,
          2.16723487e-01,  -5.00680394e-02,  -4.56055477e-02,
         -1.55026659e-01,  -1.43749550e-01,   6.21796865e-03,
          6.00050129e-02,  -1.48593277e-01,  -1.76089585e-01,
         -2.05665067e-01,   4.64819074e-02,  -9.28762779e-02,
         -4.46784281e-04,  -4.07397188e-02,  -1.85059786e-01,
         -5.50279543e-02,   1.23728728e-02,   1.77044168e-01,
          5.12257032e-02,  -4.15780097e-37,  -1.21000692e-01,
          7.72080645e-02,   1.33501709e-01,   5.58607951e-02,
         -8.31794553e-03,   1.37871355e-01,   0.00000000e+00,
        

In [4]:
test = np.float32(np.random.uniform(-2*math.pi, 2*math.pi, (1, 1))).T

print test

print sess.run(yhat, feed_dict={x:test, c:100})

[[ 5.44645929]]
[[-0.39615455]]


In [5]:
print gensin(1)

(array([[ 4.34444237]], dtype=float32), array([[-0.93306792]], dtype=float32))
